name: docker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/volkszaehler
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}

      - name: Build for test
        uses: ilteoood/docker_buildx@master
        with:
          publish: false
          imageName: ${{ secrets.DOCKERHUB_USERNAME }}/volkszaehler
          tag: latest
          dockerUser: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerPassword: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test image
        run: ./misc/dockertest/test-docker.sh

      - name: Push image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: ${{ secrets.DOCKERHUB_USERNAME }}/volkszaehler
          tag: latest
          dockerUser: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerPassword: ${{ secrets.DOCKERHUB_TOKEN }}
